kvm tools: Fix kvm/barrier.h build breakage
Ingo Molnar writes:

  On Tue, 6 Dec 2011, Ingo Molnar wrote:
  > > FYI, today's version fails to build:
  > >
  > > In file included from x86/include/kvm/barrier.h:13:0,
  > >                 from virtio/core.c:5:
  > > ../../arch/x86/include/asm/system.h:404:1: error: unknown type
  > > name ‘bool’
  > > make: *** [virtio/core.o] Error 1
  > > make: *** Waiting for unfinished jobs....
  > >
  > > latest Fedora Rawhide.
  >
  > There's no 'bool' in system.h for 3.2-rc4. Is this something that's
  > changed in -tip?

  It got introduced by a post-rc4 fix:

  e5fd47bfab2d: xen/pm_idle: Make pm_idle be default_idle under Xen.

Fix it by include <stdbool.h> in kvm/barrier.h

Reported-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Pekka Enberg <penberg@kernel.org>